services:
  gateway:
    build: ./Gateway
    ports:
      - 8080:8080
    depends_on:
      - danplanner_server

  danplanner_server:
    build: .
    ports:
      - 6000:8080
    environment:
      - ConnectionStrings__DefaultConnection=server=


  auth_service:
    build: ./AuthenticationService
    ports:
      - 6001:8080
    environment:
      - ConnectionStrings__DefaultConnection=server=